/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package the.little.bag.shop;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.html.HTML;
import static javax.swing.text.html.HTML.Attribute.ID;

/**
 *
 * @author Dulara Sandamal
 */
public class SerachItemUI extends javax.swing.JFrame {

    /**
     * Creates new form SerachItemUI
     */
    public SerachItemUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        BagListTableTwo = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SearchBagCategoryTextBox = new javax.swing.JTextField();
        SearchBagCategoryButton = new javax.swing.JButton();
        buttonexit = new javax.swing.JButton();
        buttonexit1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel10.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Bag Category");

        BagListTableTwo.setBackground(new java.awt.Color(255, 255, 255));
        BagListTableTwo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BagListTableTwo.setForeground(new java.awt.Color(0, 0, 0));
        BagListTableTwo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        BagListTableTwo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BagListTableTwoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(BagListTableTwo);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Search Item");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SearchBagCategoryTextBox.setBackground(new java.awt.Color(204, 204, 255));
        SearchBagCategoryTextBox.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N

        SearchBagCategoryButton.setBackground(new java.awt.Color(102, 102, 102));
        SearchBagCategoryButton.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        SearchBagCategoryButton.setForeground(new java.awt.Color(0, 0, 0));
        SearchBagCategoryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Serach.png"))); // NOI18N
        SearchBagCategoryButton.setText("Search");
        SearchBagCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBagCategoryButtonActionPerformed(evt);
            }
        });

        buttonexit.setBackground(new java.awt.Color(255, 255, 255));
        buttonexit.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        buttonexit.setForeground(new java.awt.Color(0, 0, 0));
        buttonexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Home.png"))); // NOI18N
        buttonexit.setText("Home");
        buttonexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonexitActionPerformed(evt);
            }
        });

        buttonexit1.setBackground(new java.awt.Color(255, 255, 255));
        buttonexit1.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        buttonexit1.setForeground(new java.awt.Color(0, 0, 0));
        buttonexit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Exit.png"))); // NOI18N
        buttonexit1.setText("Exit");
        buttonexit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonexit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(SearchBagCategoryTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(SearchBagCategoryButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonexit, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonexit1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(SearchBagCategoryTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SearchBagCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonexit, javax.swing.GroupLayout.PREFERRED_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(buttonexit1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
       public void SearchAndDisplayBagsByCategory(String category) {
    List<Bag> totalBagsList = new ArrayList<>();
    List<Bag> filteredBagsList = new ArrayList<>();  // List to hold bags matching the category
    
    try {
        File bagFile = new File("C:\\Users\\Dulara Sandamal\\Desktop\\The Little Bag Shop\\Item.txt");
        try (Scanner myReader = new Scanner(bagFile)) {
            while (myReader.hasNextLine()) {
                String bagData = myReader.nextLine();
                ArrayList<String> bagList = new ArrayList<>(Arrays.asList(bagData.split(",")));
                
                Bag bag = new Bag();
                bag.SetBagId(bagList.get(0));
                bag.SetBagName(bagList.get(1));
                bag.SetBagCategory(bagList.get(2));
                bag.SetBagPrice(Double.parseDouble(bagList.get(3)));
                totalBagsList.add(bag);
            }
        }
    } catch (FileNotFoundException e) {
        JOptionPane.showMessageDialog(null, e);
    }
    
    // Filter the bags by the specified category
    for (Bag b : totalBagsList) {
        if (b.GetBagCategory().equalsIgnoreCase(category)) {
            filteredBagsList.add(b);
        }
    }
    
    // Display the filtered list in a table
    if (filteredBagsList.isEmpty()) {
        JOptionPane.showMessageDialog(null, "No bags found for the given category.");
    } else {
        // Define the columns for the table
        String col[] = {"Bag ID", "Bag Name", "Category", "Price"};
        
        // Create a new table model with the defined columns
        DefaultTableModel tableModel = new DefaultTableModel(col, 0);
        
        // Set the model to the bagListTable
        BagListTableTwo.setModel(tableModel);
        
        // Iterate through the filtered list of bags and add each one to the table
        for (Bag b : filteredBagsList) {
            Object[] obj = {b.GetBagId(), b.GetBagName(), b.GetBagCategory(), b.GetBagPrice()};
            tableModel.addRow(obj);
        }
    }
}

  
    private void BagListTableTwoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BagListTableTwoMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BagListTableTwoMouseClicked

    private void buttonexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonexitActionPerformed
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_buttonexitActionPerformed

    private void buttonexit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonexit1ActionPerformed
        // TODO add your handling code here:
        
         System.exit(0);
    }//GEN-LAST:event_buttonexit1ActionPerformed

    private void SearchBagCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBagCategoryButtonActionPerformed
        // TODO add your handling code here:
              String category = SearchBagCategoryTextBox.getText();  
    SearchAndDisplayBagsByCategory(category);
    }//GEN-LAST:event_SearchBagCategoryButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SerachItemUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SerachItemUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SerachItemUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SerachItemUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SerachItemUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BagListTableTwo;
    private javax.swing.JButton SearchBagCategoryButton;
    private javax.swing.JTextField SearchBagCategoryTextBox;
    private javax.swing.JButton buttonexit;
    private javax.swing.JButton buttonexit1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

    private void SearchAndDisplayBagsCatagary(String category) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
